# -*- makefile -*-
#----------------------------------------------------------------------------
#       GNU ACE Workspace
#
# $Id$
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /home/quynhpp/Workspace/OpenDDS/OpenDDS/ACE_wrappers/bin/mwc.pl -type gnuace DDS.mwc
#
#----------------------------------------------------------------------------

MAKEFILE = GNUmakefile

ifeq ($(findstring k,$(MAKEFLAGS)),k)
  KEEP_GOING = -
endif

include $(ACE_ROOT)/include/makeinclude/macros.GNU

all: HelloWorld_Idl HelloWorld_Publisher HelloWorld_Subscriber

depend: HelloWorld_Idl-depend HelloWorld_Publisher-depend HelloWorld_Subscriber-depend

REMAINING_TARGETS := $(filter-out all depend,$(TARGETS_NESTED:.nested=)) $(CUSTOM_TARGETS)
.PHONY: $(REMAINING_TARGETS)

$(REMAINING_TARGETS):
	$(KEEP_GOING)@cd hello_world && $(MAKE) -f GNUmakefile.HelloWorld_Idl $(@)
	$(KEEP_GOING)@cd hello_world && $(MAKE) -f GNUmakefile.HelloWorld_Publisher $(@)
	$(KEEP_GOING)@cd hello_world && $(MAKE) -f GNUmakefile.HelloWorld_Subscriber $(@)

.PHONY: HelloWorld_Idl
HelloWorld_Idl:
	$(KEEP_GOING)@cd hello_world && $(MAKE) -f GNUmakefile.HelloWorld_Idl all

.PHONY: HelloWorld_Idl-depend
HelloWorld_Idl-depend:
	$(KEEP_GOING)@cd hello_world && $(MAKE) -f GNUmakefile.HelloWorld_Idl depend

.PHONY: HelloWorld_Publisher
HelloWorld_Publisher: HelloWorld_Idl
	$(KEEP_GOING)@cd hello_world && $(MAKE) -f GNUmakefile.HelloWorld_Publisher all

.PHONY: HelloWorld_Publisher-depend
HelloWorld_Publisher-depend:
	$(KEEP_GOING)@cd hello_world && $(MAKE) -f GNUmakefile.HelloWorld_Publisher depend

.PHONY: HelloWorld_Subscriber
HelloWorld_Subscriber: HelloWorld_Publisher
	$(KEEP_GOING)@cd hello_world && $(MAKE) -f GNUmakefile.HelloWorld_Subscriber all

.PHONY: HelloWorld_Subscriber-depend
HelloWorld_Subscriber-depend:
	$(KEEP_GOING)@cd hello_world && $(MAKE) -f GNUmakefile.HelloWorld_Subscriber depend

project_name_list:
	@echo HelloWorld_Idl
	@echo HelloWorld_Publisher
	@echo HelloWorld_Subscriber
