// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p18
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:376


#include "MyMessengerTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "MyMessengerTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for MyMessenger::MyMessageTypeSupport.

MyMessenger::MyMessageTypeSupport_ptr
TAO::Objref_Traits<MyMessenger::MyMessageTypeSupport>::duplicate (
    MyMessenger::MyMessageTypeSupport_ptr p)
{
  return MyMessenger::MyMessageTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<MyMessenger::MyMessageTypeSupport>::release (
    MyMessenger::MyMessageTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

MyMessenger::MyMessageTypeSupport_ptr
TAO::Objref_Traits<MyMessenger::MyMessageTypeSupport>::nil (void)
{
  return MyMessenger::MyMessageTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<MyMessenger::MyMessageTypeSupport>::marshal (
    const MyMessenger::MyMessageTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

MyMessenger::MyMessageTypeSupport::MyMessageTypeSupport (void)
{}

MyMessenger::MyMessageTypeSupport::~MyMessageTypeSupport (void)
{
}

MyMessenger::MyMessageTypeSupport_ptr
MyMessenger::MyMessageTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MyMessageTypeSupport::_duplicate (
      dynamic_cast<MyMessageTypeSupport_ptr> (_tao_objref)
    );
}

MyMessenger::MyMessageTypeSupport_ptr
MyMessenger::MyMessageTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MyMessageTypeSupport::_duplicate (
      dynamic_cast<MyMessageTypeSupport_ptr> (_tao_objref)
    );
}

MyMessenger::MyMessageTypeSupport_ptr
MyMessenger::MyMessageTypeSupport::_nil (void)
{
  return 0;
}

MyMessenger::MyMessageTypeSupport_ptr
MyMessenger::MyMessageTypeSupport::_duplicate (MyMessageTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
MyMessenger::MyMessageTypeSupport::_tao_release (MyMessageTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
MyMessenger::MyMessageTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:MyMessenger/MyMessageTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* MyMessenger::MyMessageTypeSupport::_interface_repository_id (void) const
{
  return "IDL:MyMessenger/MyMessageTypeSupport:1.0";
}

::CORBA::Boolean
MyMessenger::MyMessageTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for MyMessenger::MyMessageDataWriter.

MyMessenger::MyMessageDataWriter_ptr
TAO::Objref_Traits<MyMessenger::MyMessageDataWriter>::duplicate (
    MyMessenger::MyMessageDataWriter_ptr p)
{
  return MyMessenger::MyMessageDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<MyMessenger::MyMessageDataWriter>::release (
    MyMessenger::MyMessageDataWriter_ptr p)
{
  ::CORBA::release (p);
}

MyMessenger::MyMessageDataWriter_ptr
TAO::Objref_Traits<MyMessenger::MyMessageDataWriter>::nil (void)
{
  return MyMessenger::MyMessageDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<MyMessenger::MyMessageDataWriter>::marshal (
    const MyMessenger::MyMessageDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

MyMessenger::MyMessageDataWriter::MyMessageDataWriter (void)
{}

MyMessenger::MyMessageDataWriter::~MyMessageDataWriter (void)
{
}

MyMessenger::MyMessageDataWriter_ptr
MyMessenger::MyMessageDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MyMessageDataWriter::_duplicate (
      dynamic_cast<MyMessageDataWriter_ptr> (_tao_objref)
    );
}

MyMessenger::MyMessageDataWriter_ptr
MyMessenger::MyMessageDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MyMessageDataWriter::_duplicate (
      dynamic_cast<MyMessageDataWriter_ptr> (_tao_objref)
    );
}

MyMessenger::MyMessageDataWriter_ptr
MyMessenger::MyMessageDataWriter::_nil (void)
{
  return 0;
}

MyMessenger::MyMessageDataWriter_ptr
MyMessenger::MyMessageDataWriter::_duplicate (MyMessageDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
MyMessenger::MyMessageDataWriter::_tao_release (MyMessageDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
MyMessenger::MyMessageDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:MyMessenger/MyMessageDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* MyMessenger::MyMessageDataWriter::_interface_repository_id (void) const
{
  return "IDL:MyMessenger/MyMessageDataWriter:1.0";
}

::CORBA::Boolean
MyMessenger::MyMessageDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// be/be_visitor_interface/interface_cs.cpp:51

// Traits specializations for MyMessenger::MyMessageDataReader.

MyMessenger::MyMessageDataReader_ptr
TAO::Objref_Traits<MyMessenger::MyMessageDataReader>::duplicate (
    MyMessenger::MyMessageDataReader_ptr p)
{
  return MyMessenger::MyMessageDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<MyMessenger::MyMessageDataReader>::release (
    MyMessenger::MyMessageDataReader_ptr p)
{
  ::CORBA::release (p);
}

MyMessenger::MyMessageDataReader_ptr
TAO::Objref_Traits<MyMessenger::MyMessageDataReader>::nil (void)
{
  return MyMessenger::MyMessageDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<MyMessenger::MyMessageDataReader>::marshal (
    const MyMessenger::MyMessageDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

MyMessenger::MyMessageDataReader::MyMessageDataReader (void)
{}

MyMessenger::MyMessageDataReader::~MyMessageDataReader (void)
{
}

MyMessenger::MyMessageDataReader_ptr
MyMessenger::MyMessageDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MyMessageDataReader::_duplicate (
      dynamic_cast<MyMessageDataReader_ptr> (_tao_objref)
    );
}

MyMessenger::MyMessageDataReader_ptr
MyMessenger::MyMessageDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return MyMessageDataReader::_duplicate (
      dynamic_cast<MyMessageDataReader_ptr> (_tao_objref)
    );
}

MyMessenger::MyMessageDataReader_ptr
MyMessenger::MyMessageDataReader::_nil (void)
{
  return 0;
}

MyMessenger::MyMessageDataReader_ptr
MyMessenger::MyMessageDataReader::_duplicate (MyMessageDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
MyMessenger::MyMessageDataReader::_tao_release (MyMessageDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
MyMessenger::MyMessageDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:MyMessenger/MyMessageDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* MyMessenger::MyMessageDataReader::_interface_repository_id (void) const
{
  return "IDL:MyMessenger/MyMessageDataReader:1.0";
}

::CORBA::Boolean
MyMessenger::MyMessageDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

