// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p18
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// be/be_codegen.cpp:152

#ifndef _TAO_IDL_MYMESSENGERTYPESUPPORTC_1ZL09Q_H_
#define _TAO_IDL_MYMESSENGERTYPESUPPORTC_1ZL09Q_H_

#include /**/ "ace/pre.h"


#include /**/ "ace/config-all.h"

#if !defined (ACE_LACKS_PRAGMA_ONCE)
# pragma once
#endif /* ACE_LACKS_PRAGMA_ONCE */


#include "tao/ORB.h"
#include "tao/SystemException.h"
#include "tao/Basic_Types.h"
#include "tao/ORB_Constants.h"
#include "dds/DCPS/ZeroCopyInfoSeq_T.h"
#include "dds/DCPS/ZeroCopySeq_T.h"
#include "tao/Object.h"
#include "tao/String_Manager_T.h"
#include "tao/Sequence_T.h"
#include "tao/Objref_VarOut_T.h"
#include "tao/Seq_Var_T.h"
#include "tao/Seq_Out_T.h"
#include "tao/Arg_Traits_T.h"
#include "tao/Basic_Arguments.h"
#include "tao/Special_Basic_Arguments.h"
#include "tao/Any_Insert_Policy_T.h"
#include "tao/Fixed_Size_Argument_T.h"
#include "tao/Var_Size_Argument_T.h"
#include /**/ "tao/Version.h"
#include /**/ "tao/Versioned_Namespace.h"

#include "MyMessengerC.h"
#include "dds/DdsDcpsInfrastructureC.h"
#include "dds/DdsDcpsPublicationC.h"
#include "dds/DdsDcpsSubscriptionExtC.h"
#include "dds/DdsDcpsTopicC.h"
#include "dds/DdsDcpsTypeSupportExtC.h"

#if TAO_MAJOR_VERSION != 2 || TAO_MINOR_VERSION != 2 || TAO_BETA_VERSION != 0
#error This file should be regenerated with TAO_IDL
#endif

#if defined (TAO_EXPORT_MACRO)
#undef TAO_EXPORT_MACRO
#endif
#define TAO_EXPORT_MACRO 

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:38

namespace MyMessenger
{

  // TAO_IDL - Generated from
  // be/be_visitor_sequence/sequence_ch.cpp:102

  typedef ::TAO::DCPS::ZeroCopyDataSeq< MyMessenger::MyMessage, DCPS_ZERO_COPY_SEQ_DEFAULT_SIZE> MyMessageSeq;
  

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_MYMESSENGER_MYMESSAGETYPESUPPORT__VAR_OUT_CH_)
#define _MYMESSENGER_MYMESSAGETYPESUPPORT__VAR_OUT_CH_

  class MyMessageTypeSupport;
  typedef MyMessageTypeSupport *MyMessageTypeSupport_ptr;

  typedef
    TAO_Objref_Var_T<
        MyMessageTypeSupport
      >
    MyMessageTypeSupport_var;
  
  typedef
    TAO_Objref_Out_T<
        MyMessageTypeSupport
      >
    MyMessageTypeSupport_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  MyMessageTypeSupport
    : public virtual ::OpenDDS::DCPS::TypeSupport
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef MyMessageTypeSupport_ptr _ptr_type;
    typedef MyMessageTypeSupport_var _var_type;
    typedef MyMessageTypeSupport_out _out_type;

    // The static operations.
    static MyMessageTypeSupport_ptr _duplicate (MyMessageTypeSupport_ptr obj);

    static void _tao_release (MyMessageTypeSupport_ptr obj);

    static MyMessageTypeSupport_ptr _narrow (::CORBA::Object_ptr obj);
    static MyMessageTypeSupport_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MyMessageTypeSupport_ptr _nil (void);

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MyMessageTypeSupport (void);

    

    virtual ~MyMessageTypeSupport (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    MyMessageTypeSupport (const MyMessageTypeSupport &);

    void operator= (const MyMessageTypeSupport &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_MYMESSENGER_MYMESSAGEDATAWRITER__VAR_OUT_CH_)
#define _MYMESSENGER_MYMESSAGEDATAWRITER__VAR_OUT_CH_

  class MyMessageDataWriter;
  typedef MyMessageDataWriter *MyMessageDataWriter_ptr;

  typedef
    TAO_Objref_Var_T<
        MyMessageDataWriter
      >
    MyMessageDataWriter_var;
  
  typedef
    TAO_Objref_Out_T<
        MyMessageDataWriter
      >
    MyMessageDataWriter_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  MyMessageDataWriter
    : public virtual ::DDS::DataWriter
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef MyMessageDataWriter_ptr _ptr_type;
    typedef MyMessageDataWriter_var _var_type;
    typedef MyMessageDataWriter_out _out_type;

    // The static operations.
    static MyMessageDataWriter_ptr _duplicate (MyMessageDataWriter_ptr obj);

    static void _tao_release (MyMessageDataWriter_ptr obj);

    static MyMessageDataWriter_ptr _narrow (::CORBA::Object_ptr obj);
    static MyMessageDataWriter_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MyMessageDataWriter_ptr _nil (void);

    virtual ::DDS::InstanceHandle_t register_instance (
      const ::MyMessenger::MyMessage & instance) = 0;

    virtual ::DDS::InstanceHandle_t register_instance_w_timestamp (
      const ::MyMessenger::MyMessage & instance,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance (
      const ::MyMessenger::MyMessage & instance,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t unregister_instance_w_timestamp (
      const ::MyMessenger::MyMessage & instance,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & timestamp) = 0;

    virtual ::DDS::ReturnCode_t write (
      const ::MyMessenger::MyMessage & instance_data,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::ReturnCode_t write_w_timestamp (
      const ::MyMessenger::MyMessage & instance_data,
      ::DDS::InstanceHandle_t handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t dispose (
      const ::MyMessenger::MyMessage & instance_data,
      ::DDS::InstanceHandle_t instance_handle) = 0;

    virtual ::DDS::ReturnCode_t dispose_w_timestamp (
      const ::MyMessenger::MyMessage & instance_data,
      ::DDS::InstanceHandle_t instance_handle,
      const ::DDS::Time_t & source_timestamp) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::MyMessenger::MyMessage & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::MyMessenger::MyMessage & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MyMessageDataWriter (void);

    

    virtual ~MyMessageDataWriter (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    MyMessageDataWriter (const MyMessageDataWriter &);

    void operator= (const MyMessageDataWriter &);
  };

  // TAO_IDL - Generated from
  // be/be_interface.cpp:751

#if !defined (_MYMESSENGER_MYMESSAGEDATAREADER__VAR_OUT_CH_)
#define _MYMESSENGER_MYMESSAGEDATAREADER__VAR_OUT_CH_

  class MyMessageDataReader;
  typedef MyMessageDataReader *MyMessageDataReader_ptr;

  typedef
    TAO_Objref_Var_T<
        MyMessageDataReader
      >
    MyMessageDataReader_var;
  
  typedef
    TAO_Objref_Out_T<
        MyMessageDataReader
      >
    MyMessageDataReader_out;

#endif /* end #if !defined */

  // TAO_IDL - Generated from
  // be/be_visitor_interface/interface_ch.cpp:43

  class  MyMessageDataReader
    : public virtual ::OpenDDS::DCPS::DataReaderEx
  
  {
  public:

    // TAO_IDL - Generated from
    // be/be_type.cpp:307

    typedef MyMessageDataReader_ptr _ptr_type;
    typedef MyMessageDataReader_var _var_type;
    typedef MyMessageDataReader_out _out_type;

    // The static operations.
    static MyMessageDataReader_ptr _duplicate (MyMessageDataReader_ptr obj);

    static void _tao_release (MyMessageDataReader_ptr obj);

    static MyMessageDataReader_ptr _narrow (::CORBA::Object_ptr obj);
    static MyMessageDataReader_ptr _unchecked_narrow (::CORBA::Object_ptr obj);
    static MyMessageDataReader_ptr _nil (void);

    virtual ::DDS::ReturnCode_t read (
      ::MyMessenger::MyMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take (
      ::MyMessenger::MyMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_w_condition (
      ::MyMessenger::MyMessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_w_condition (
      ::MyMessenger::MyMessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_sample (
      ::MyMessenger::MyMessage & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t take_next_sample (
      ::MyMessenger::MyMessage & received_data,
      ::DDS::SampleInfo & sample_info) = 0;

    virtual ::DDS::ReturnCode_t read_instance (
      ::MyMessenger::MyMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_instance (
      ::MyMessenger::MyMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_instance_w_condition (
      ::MyMessenger::MyMessageSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_instance_w_condition (
      ::MyMessenger::MyMessageSeq & received_data,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance (
      ::MyMessenger::MyMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance (
      ::MyMessenger::MyMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t a_handle,
      ::DDS::SampleStateMask sample_states,
      ::DDS::ViewStateMask view_states,
      ::DDS::InstanceStateMask instance_states) = 0;

    virtual ::DDS::ReturnCode_t read_next_instance_w_condition (
      ::MyMessenger::MyMessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t take_next_instance_w_condition (
      ::MyMessenger::MyMessageSeq & data_values,
      ::DDS::SampleInfoSeq & sample_infos,
      ::CORBA::Long max_samples,
      ::DDS::InstanceHandle_t previous_handle,
      ::DDS::ReadCondition_ptr a_condition) = 0;

    virtual ::DDS::ReturnCode_t return_loan (
      ::MyMessenger::MyMessageSeq & received_data,
      ::DDS::SampleInfoSeq & info_seq) = 0;

    virtual ::DDS::ReturnCode_t get_key_value (
      ::MyMessenger::MyMessage & key_holder,
      ::DDS::InstanceHandle_t handle) = 0;

    virtual ::DDS::InstanceHandle_t lookup_instance (
      const ::MyMessenger::MyMessage & instance_data) = 0;

    // TAO_IDL - Generated from
    // be/be_visitor_interface/interface_ch.cpp:140

    virtual ::CORBA::Boolean _is_a (const char *type_id);
    virtual const char* _interface_repository_id (void) const;
    virtual ::CORBA::Boolean marshal (TAO_OutputCDR &cdr);
  
  protected:
    // Abstract or local interface only.
    MyMessageDataReader (void);

    

    virtual ~MyMessageDataReader (void);
  
  private:
    // Private and unimplemented for concrete interfaces.
    MyMessageDataReader (const MyMessageDataReader &);

    void operator= (const MyMessageDataReader &);
  };

// TAO_IDL - Generated from
// be/be_visitor_module/module_ch.cpp:67

} // module MyMessenger

// TAO_IDL - Generated from
// be/be_visitor_arg_traits.cpp:68

TAO_BEGIN_VERSIONED_NAMESPACE_DECL


// Arg traits specializations.
namespace TAO
{
}

TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_visitor_traits.cpp:62

TAO_BEGIN_VERSIONED_NAMESPACE_DECL

// Traits specializations.
namespace TAO
{

#if !defined (_MYMESSENGER_MYMESSAGETYPESUPPORT__TRAITS_)
#define _MYMESSENGER_MYMESSAGETYPESUPPORT__TRAITS_

  template<>
  struct  Objref_Traits< ::MyMessenger::MyMessageTypeSupport>
  {
    static ::MyMessenger::MyMessageTypeSupport_ptr duplicate (
        ::MyMessenger::MyMessageTypeSupport_ptr p);
    static void release (
        ::MyMessenger::MyMessageTypeSupport_ptr p);
    static ::MyMessenger::MyMessageTypeSupport_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::MyMessenger::MyMessageTypeSupport_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_MYMESSENGER_MYMESSAGEDATAWRITER__TRAITS_)
#define _MYMESSENGER_MYMESSAGEDATAWRITER__TRAITS_

  template<>
  struct  Objref_Traits< ::MyMessenger::MyMessageDataWriter>
  {
    static ::MyMessenger::MyMessageDataWriter_ptr duplicate (
        ::MyMessenger::MyMessageDataWriter_ptr p);
    static void release (
        ::MyMessenger::MyMessageDataWriter_ptr p);
    static ::MyMessenger::MyMessageDataWriter_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::MyMessenger::MyMessageDataWriter_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */

#if !defined (_MYMESSENGER_MYMESSAGEDATAREADER__TRAITS_)
#define _MYMESSENGER_MYMESSAGEDATAREADER__TRAITS_

  template<>
  struct  Objref_Traits< ::MyMessenger::MyMessageDataReader>
  {
    static ::MyMessenger::MyMessageDataReader_ptr duplicate (
        ::MyMessenger::MyMessageDataReader_ptr p);
    static void release (
        ::MyMessenger::MyMessageDataReader_ptr p);
    static ::MyMessenger::MyMessageDataReader_ptr nil (void);
    static ::CORBA::Boolean marshal (
        const ::MyMessenger::MyMessageDataReader_ptr p,
        TAO_OutputCDR & cdr);
  };

#endif /* end #if !defined */
}
TAO_END_VERSIONED_NAMESPACE_DECL



// TAO_IDL - Generated from
// be/be_codegen.cpp:1703
#if defined (__ACE_INLINE__)
#include "MyMessengerTypeSupportC.inl"
#endif /* defined INLINE */

#include /**/ "ace/post.h"

#endif /* ifndef */

